### ISSUE TITLE
Snarl notification not always working

### ISSUE THREAD

**Issue by dcendents** [jcgay/maven-notifier#13]
Hi,

There are a few scenarios when the snarl notification does not work: 
  * When launching simultaneous builds: only the first one will have a notification, the second will print a warning: Failed to notify...
  * If a build is stopped (CTRL-C), then no further notification will work until Snarl is restarted.

If I understood the problem correctly, I believe this is caused by the maven-notifier that generates a new completely random password when registering with Snarl while always using the same application id.

This prevents the second process from notifying as the password does not match, and if maven does not correctly unregister itself at the end of the build then no more notification will occur (password will never match).

From what I could see:

register?password=ad897f06-22f7-4e77-b20f-84cf952f5207&app-sig=application/x-vnd-apache.maven&uid=c62ae50e-2824-4d9b-9ced-acad75826924&title=Maven

unregister?password=ad897f06-22f7-4e77-b20f-84cf952f5207&app-sig=application/x-vnd-apache.maven

Maybe using a random app-sig would fix the problem?

Thanks

**Comment by jcgay** [comment]
I have to read again the Snarl guidelines but this random password using the same application id seems like a bad idea for multiple instances of the same application.

Using a random app-sig could do the trick but what about customisation (I don't have a windows box with Snarl actually to verify) ? You can configure how notification works per application with Snarl ?

Maybe we can register/unregister the application just before/after sending the notification, it will limit the risk of multiple registration and the ctrl-c problem. In the maven-notifier case we only send one notification anyway.

Thanks for the detailed report !

I'll have time to deal with it in two weeks or so.

**Comment by dcendents** [comment]
If you want to test on windows you can always download a VM image here: http://dev.modern.ie/tools/vms/windows/. They are valid for 3 months until windows complain you do not have a valid key and then you need to start from scratch again. They are normally meant to test web applications under different IE versions but you can use them anyway.

Regarding customisation, I don't think we can customise it. I'm new to snarl but I cannot see anything regarding maven. You can customise plugins but I don't know where/how to customise registered applications.

If I understand the password correctly, this is to prevent another application from impersonating you. So hard-coding a password wouldn't work as it is an open source project. What about adding a property in the maven-notifier.properties file to set the password to use? This way it becomes the responsibility of the user to secure his file.

So you wouldn't need to modify the app-sig and you can leave the app registered all the time.

Let me know if you like this idea, I might have time to work on it and submit a PR.

**Comment by jcgay** [comment]
If there is really no way to customize Snarl by application, generating a unique application id per run should not be a big deal. Even if the application is not unregistered (ctrl-c or whatever), Snarl has a garbage collector to remove old registered applications.

Else your proposition is a good way to go. Also I would like to have a default configuration which works without user configuration (so maybe in that case I would remove the generated password).

I'm not home (without my laptop, that's why I don't have windows vm :p) so I didn't have much time to look at it right now but If you're willing to implement the patch I'll be glad to merge it when I'll be back !

Thanks !

**Comment by jcgay** [comment]
Holidays are over, so I got time to look into it.

There is a way in Snarl to configure how notifications are displayed per application. This is in Snarl Preferences, the Applications tab. So we can't generate a random appsig per Maven launch. It would disable user customization.

So I have implemented your suggestion. By default no application password is set, this is let to user discretion. This is not perfect neither since any "malicious" application could just read the password in `maven-notifier.properties` but it should be ok for now :)

**Comment by jcgay** [comment]
Fixed in v1.8

**Comment by dcendents** [comment]
Thanks,

Sorry I was on paternity leave so I didn't get a chance to try it before. It seems to fix all the problems I had thanks

**Comment by jcgay** [comment]
Cool !
Thanks again for your time.
