### ISSUE TITLE
How to notify asynchronously?

### ISSUE THREAD

**Issue by michaldo** [jcgay/maven-notifier#15]
On my computer (Windows10) command line terminal waits until notification is closed. 
Is it possible to launch notification message and **immediately** return to user caret?

**Comment by jcgay** [comment]
I assume you are using the default notifier [System Tray](https://github.com/jcgay/send-notification/wiki/System-tray) (which may look really different on Windows) ? 
Because this notifier is implemented in Java and is running in the same JVM as Maven, this is why it waits when the build ends. If not you'll will not see any notification as the JVM just exits. 

You can pick a different [notifier](https://github.com/jcgay/maven-notifier#notifiers) for Windows (like [Snarl](https://github.com/jcgay/send-notification/wiki/Snarl), [Growl](https://github.com/jcgay/send-notification/wiki/Growl-(Windows)), etc.). They will not block your command line. 

Let me know if it helps.
Thanks

**Comment by michaldo** [comment]
Yes it helps. 
Thanks
