### ISSUE TITLE
Mac OS X - Terminal / Java window

### ISSUE THREAD

**Issue by brunocvcunha** [jcgay/maven-notifier#16]
Hi!

I really loved your project! The whole maven-deluxe bundle is awesome!

Just came across an annoying thing in the notifier plugin.
It uses terminal-notifier and I'm able to see the notification, but when I click on it, it opens the Apple's Terminal, but I'm using iTerm2.
So I can't click in the notification, because it takes me to a terminal that I don't use.

I see in the class `fr.jcgay.notification.notifier.notificationcenter.TerminalNotifierConfiguration` that you explicitly use `com.apple.Terminal`, but I still didn't figure how do you chain everything together and if it's possible to refer to the process that called Maven.

Another thing is that after installing your package through brew, with the following links:

> # maven-color, maven-notifier and maven-profiler
> brew tap jcgay/jcgay
> brew install maven-deluxe
> brew link --overwrite maven-deluxe

I noticed a few things:
- I already had Maven 3.3.9 installed and brew had to download it again.
- Now it switched to a Desktop version of Java, and everytime that I run Maven, I can see the Java icon in the Dock. I'm able to disable it by forcing -Djava.awt.headless=true: `MAVEN_OPTS="-Djava.awt.headless=true" mvn clean install` but I'm also not sure of what caused it.

Thank you.
Regards,
Bruno Candido Volpato da Cunha

**Comment by jcgay** [comment]
Thanks for the kind words!

You can configure which application will be opened when clicking a notification with the property:

    notifier.notification-center.activate

It is documented [here](https://github.com/jcgay/send-notification/wiki/terminal-notifier), sadly the configuration is static, I didn't find a way to capture which application has launched `mvn`. Maybe you know one ?

For the brew formula, as I need to enhance a `mvn` installation with libs, I choose to not modify any previous `mvn` installation. You can always switch back to a vanilla `mvn` if something goes wrong. This is why you noticed that brew has downloaded again `mvn`. Maybe I can benefit from previous download with `brew` but I don't know how to do that (I'll give it a look).  

I remember having a lot of Java application displaying a dock icon when not needed so that I also have `-Djava.awt.headless=true` everywhere in my environment. I will remove it and investigate why `maven-notifier` messes with it (it should be linked to the `SystemTray` notifier).

Thanks!

**Comment by jcgay** [comment]
Just realized that I have forgot to ping back after releasing `maven-notifier 1.9` 👎 
Have you been able to give it a try ? Does it prevent Java to display an icon in the dock ?

**Comment by brunocvcunha** [comment]
Hi @jcgay 

Sorry for the long time to reply back.
I tested with 1.9.1 and if I remove the `-Djava.awt.headless=true` the Java icon still shows up in the dock.

```
brunovolpato@BR-MacBook-Pro[/tmp]+ mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)
Maven home: /usr/local/Cellar/maven-deluxe/3.3.9-6/libexec
Java version: 1.8.0_92, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"

brunovolpato@BR-MacBook-Pro[/tmp]+ ls -la /usr/local/Cellar/maven-deluxe/3.3.9-6/libexec/lib/ext
total 22992
drwxr-xr-x  11 brunovolpato  staff      374 Nov  1 21:16 .
drwxr-xr-x  75 brunovolpato  staff     2550 Nov  1 21:16 ..
-rw-r--r--   1 brunovolpato  staff      152 Nov 10  2015 README.txt
-rw-r--r--   1 brunovolpato  staff  4550894 Nov  1 21:16 groovy-2.4.7.jar
-rw-r--r--   1 brunovolpato  staff   151874 Nov  1 21:16 jansi-1.13.jar
-rw-r--r--   1 brunovolpato  staff   280928 Nov  1 21:16 logback-classic-1.1.3.jar
-rw-r--r--   1 brunovolpato  staff   455041 Nov  1 21:16 logback-core-1.1.3.jar
-rw-r--r--   1 brunovolpato  staff    12494 Nov  1 21:16 maven-color-core-1.6.0.jar
-rw-r--r--   1 brunovolpato  staff     8097 Nov  1 21:16 maven-color-logback-1.6.0.jar
-rw-r--r--@  1 brunovolpato  staff  3800951 Nov  1 22:41 maven-notifier-1.9.1-shaded.jar
-rw-r--r--   1 brunovolpato  staff  2486459 Oct 24  2015 maven-profiler-2.4-shaded.jar
```

**Comment by jcgay** [comment]
No problem :)

Which notifier are you using ?

I have two of them where I just can't prevent dock icon creation: `Growl` and `SystemTray`. 
`SystemTray` because it is using `AWT` and `Growl` because the library I have used relies on `AWT` API. 

`AnyBar` needs to resize images. This is done at first launch in a temporary folder, it displays an icon but future launch should be fine until the temporary folder is cleaned up.

Other notifiers should not depends on `AWT` and should not add an icon in the dock.

**Comment by brunocvcunha** [comment]
I'm using `terminal-notifier`.

**Comment by jcgay** [comment]
I have just retested it with `terminal-notifier` and I don't have any Java icon appearing in the dock.

Can you launch your build without `maven-notifier` to verify that it is not coming from somewhere else ?
